### ISSUE TITLE
Builds fail when using Azure CosmosDB

### ISSUE THREAD

**Issue by charlestbell** [expo/eas-build#121]
Let me explain,

The JS SQL SDK for Azure Cosmos DB is called @azure/cosmos.
@azure/cosmo is dependent on a package called isomorphic-webcrypto, and that package depends on the real problem, which is @unimodules/core

@unimodules/core throws an error in when running `eas build`.
❌ ld: 12 duplicate symbols for architecture arm64
It's well documented here: https://github.com/kevlened/isomorphic-webcrypto/issues/65

I found a workaround, which is to use the Classic Expo build service. But it is deprecated and earmarked to go offline in 160 days or so.
 
Can you please update EAS Build to work like Classic and not have this error? Or, less-optimally, not deprecate the classic build service?

I asked the @azure/cosmos guys about removing the isomorphic-webcrypto polyfill from, but it doesn't seem like there isn't a worthy replacement at the moment, and since Classic build works right now, it seems like a patch to EAS Build is likely the best path to go down.

 https://github.com/Azure/azure-sdk-for-js/issues/22628
 
 Thank you for all your amazing work!

**Comment by wkozyra95** [comment]
> @unimodules/core throws an error in when running eas build.

If it does not work on eas then it also does not work when building locally in xcode or android studio, it is clear bug in a library and should be addressed there.

> Can you please update EAS Build to work like Classic and not have this error? 

It works in classic builds because we ignore any native code that packages have and just build the same prebuild for all users, and just replace js. The whole point of eas was to allow users to introduce native changes, so what you are asking would basically downgrade EAS Build to the same capabilities as the classic build service.

> Or, less-optimally, not deprecate the classic build service?

There will be no new SDKs after 46 for it, I'm not sure if the publically announced date is final, so maybe if there won't be much maintenance cost we may keep it up a bit longer if there is still significant usage. Also, there is turtle-cli that you can use to build on your own machine.

**Comment by charlestbell** [comment]
So if I never upgrade from sdk 45, I'll be ok?

**Comment by wkozyra95** [comment]
even after we close our service you will be able to run classic builds up to sdk 46 on your own machine using turtle-cli, but at this point e.g. if sth changes in apple/android policies those versions might no longer be accepted in store
